export const PRE_DEFINE_PROJECT_CONFIG = Symbol.for('PRE_DEFINE_PROJECT_CONFIG')
export const EXPORT_DEFAULT_FUNCTION_ALIAS = '$default'
export const USE_INPUT_METADATA = 'USE_INPUT_METADATA'
export const DECORATE_BASE_PATH = '/rpc'
