/**
 * Now the function accepts all http methods
 * @deprecated will be removed in next major version.
 */
export type ApiHttpMethod = 'GET' | 'POST'

export type ApiBaseParam = {
  /**
   * @description generated by the file router, base on file path
   */
  functionId?: string
  data?: {
    args: any[]
    [key: string]: any
  }
}

export interface ApiParam extends ApiBaseParam {
  url: string
  /**
   * Now the function accepts all http methods
   * @deprecated will be removed in next major version.
   */
  method: ApiHttpMethod

  meta: {
    functionName?: string
    [key: string]: any
  }
}
