/**
 * Now the function accepts all http methods
 * @deprecated will be removed in next major version.
 */
export type ApiHttpMethod = 'GET' | 'POST'

export type ApiBaseParam = {
  /**
   * @description generated by the file router, base on file path
   */
  functionId?: string
}

export interface ApiParam extends ApiBaseParam {
  url: string
  /**
   * Now the function accepts all http methods
   * @deprecated will be removed in next major version.
   */
  method: ApiHttpMethod
  data: {
    args: any[]
    [key: string]: any
  }
  meta: {
    functionName?: string
    superjson?: boolean
    [key: string]: any
  }
}
