#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn pretty-quick --staged

if [ -f yarn.lock ]; then
  if grep -q 'registry.npm.alibaba-inc.com' yarn.lock; then
    echo 'yarn.lock contains "registry.npm.alibaba-inc.com"'
    exit 1
  fi
fi
