# ref: https://github.com/midwayjs/midway/blob/main/.github/workflows/site.yml#L7

name: Site

on:
  push:
    branches: [main]
    paths: [docs/**]

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: '📦 Update Hooks Docs'
    steps:
      - uses: passeidireto/trigger-external-workflow-action@main
        env:
          PAYLOAD_AUTHOR: ${{ github.author }}
          PAYLOAD_REVISION: '3'
        with:
          repository: midwayjs/midway
          event: update-hooks-docs
          github_pat: ${{ secrets.GOD }}
